I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 87, in script
    if renpy.emscripten.run_script_int("login(username,password)"):
  File "game/script.rpy", line 87, in <module>
    if renpy.emscripten.run_script_int("login(username,password)"):
AttributeError: 'bool' object has no attribute 'run_script_int'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 87, in script
    if renpy.emscripten.run_script_int("login(username,password)"):
  File "C:\Users\SSAFY\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\SSAFY\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\SSAFY\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 87, in <module>
    if renpy.emscripten.run_script_int("login(username,password)"):
AttributeError: 'bool' object has no attribute 'run_script_int'

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
dongjin_love 1.0
Tue May 14 11:41:15 2024
